### ISSUE TITLE
Factory reset protection doesn't work

### ISSUE THREAD

**Issue by Blystad** [opengapps/aosp_build#115]
(Probably, I don't really have a way to confirm 100%)

I think we need to set:
https://github.com/android-ia/vendor_intel_common/blob/master/boot/overlay/frameworks/base/core/res/res/values/config.xml

**Comment by jamuir** [comment]
I think you're right.

I've noticed the following logcat error message in our in-house builds for a few weeks:

```
09-12 20:10:38.431 I/SystemServiceManager( 1521): u0 : Starting com.android.server.PersistentDataBlockService
09-12 20:10:38.460 E/PersistentDataBlockService( 1521): u0 : not able to find package 
09-12 20:10:38.460 E/PersistentDataBlockService( 1521): android.content.pm.PackageManager$NameNotFoundException: 
09-12 20:10:38.460 E/PersistentDataBlockService( 1521):         at android.app.ApplicationPackageManager.getPackageUid(ApplicationPackageManager.java:231)
09-12 20:10:38.460 E/PersistentDataBlockService( 1521):         at com.android.server.PersistentDataBlockService.getAllowedUid(PersistentDataBlockService.java:96)
09-12 20:10:38.460 E/PersistentDataBlockService( 1521):         at com.android.server.PersistentDataBlockService.<init>(PersistentDataBlockService.java:87)
09-12 20:10:38.460 E/PersistentDataBlockService( 1521):         at java.lang.reflect.Constructor.newInstance(Native Method)
09-12 20:10:38.460 E/PersistentDataBlockService( 1521):         at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:89)
09-12 20:10:38.460 E/PersistentDataBlockService( 1521):         at com.android.server.SystemServer.startOtherServices(SystemServer.java:636)
09-12 20:10:38.460 E/PersistentDataBlockService( 1521):         at com.android.server.SystemServer.run(SystemServer.java:281)
09-12 20:10:38.460 E/PersistentDataBlockService( 1521):         at com.android.server.SystemServer.main(SystemServer.java:179)
09-12 20:10:38.460 E/PersistentDataBlockService( 1521):         at java.lang.reflect.Method.invoke(Native Method)
09-12 20:10:38.460 E/PersistentDataBlockService( 1521):         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-12 20:10:38.460 E/PersistentDataBlockService( 1521):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
