### ISSUE TITLE
Play Store stuck on "Download pending..."

### ISSUE THREAD

**Issue by jamuir** [opengapps/aosp_build#184]
A number of people have hit the following issue with Play Store in Oreo:

-After the device boots, connect to wifi, then open Play Store and log in.
-Find an app and try to install it.
-Play Store does not install the app, but instead shows "Download pending..." for an indefinite amount of time.
-You can work around this by killing Play Store (from the recent apps menu) and then reopening it.

[logcat-0.txt](https://github.com/opengapps/aosp_build/files/2160754/logcat-0.txt)

![sc-8613](https://user-images.githubusercontent.com/5332385/42240608-d64eeb42-7ed5-11e8-9964-60c59c930318.png)
![sc-8762](https://user-images.githubusercontent.com/5332385/42240603-d17b10fa-7ed5-11e8-9cb3-f22d6213ba71.png)

**Comment by jamuir** [comment]
It has been reported that this does not happen if you install gapps using one of the zip packages (but I have not confirmed this myself).

**Comment by phhusson** [comment]
Here is a failing integration:
https://github.com/phhusson/device_phh_treble/blob/361aedfd203c5c0bc74ba956ee14f19bc677283f/gapps.mk

So that's a "nano" gapps_variant, with few manual additions

(the "phh-override" package only removes "webview" and "WebViewGoogle" packages, cf https://github.com/opengapps/aosp_build/issues/161#issuecomment-361003979)

**Comment by jamuir** [comment]
@Blystad @alviteri :  have you encountered this as well?

From the logcat I posted, it looks like Play Store is trying to display a billing-info view, but that fails (see below).  Maybe something gets broken during dex-optimization.  I will try disabling dex-opt to see if it makes a difference.

```
07-03 18:55:46.044 I/AppCompatDelegate( 9023): u0 : Failed to instantiate custom view inflater android.support.v7.app.AppCompatViewInflater. Falling back to default.
07-03 18:55:46.044 I/AppCompatDelegate( 9023): java.lang.ClassNotFoundException: android.support.v7.app.AppCompatViewInflater
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at java.lang.Class.classForName(Native Method)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at java.lang.Class.forName(Class.java:453)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at java.lang.Class.forName(Class.java:378)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at android.support.v7.app.aa.a(SourceFile:334)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at android.support.v7.app.aa.onCreateView(SourceFile:696)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:1933)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2586)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2659)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2067)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at android.view.Window.findViewById(Window.java:1359)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at com.google.android.finsky.r.a.P(SourceFile:376)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at com.google.android.finsky.r.a.onCreate(SourceFile:212)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at com.google.android.finsky.billing.lightpurchase.LightPurchaseFlowActivity.onCreate(SourceFile:667)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at android.app.Activity.performCreate(Activity.java:6999)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at android.app.Activity.performCreate(Activity.java:6990)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at android.os.Looper.loop(Looper.java:164)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at java.lang.reflect.Method.invoke(Native Method)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.app.AppCompatViewInflater" on path: DexPathList[[zip file "/data/app/com.android.vending-MEkK1WZuvjNmCAq3Za0ySA==/base.apk"],nativeLibraryDirectories=[/data/app/com.android.vending-MEkK1WZuvjNmCAq3Za0ySA==/lib/arm, /data/app/com.android.vending-MEkK1WZuvjNmCAq3Za0ySA==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-03 18:55:46.044 I/AppCompatDelegate( 9023): 	... 31 more
```

**Comment by alviteri** [comment]
Hi @jamuir yeah the problem is present as well only using aosp_build ... Zips are ok

**Comment by alviteri** [comment]
And no ... Dex-optimization is not the problem ... Already tested

**Comment by Blystad** [comment]
I don't see this issue at all on Nougat.

Does it just happen on Oreo?

I would either attach a debugger to Class.forName for the com.android.vending package and see how it's handled when installed using opengapps vs zip file. Or, add some logging and see where the class is resolved to.

If I recall correctly then I think at Google IO Google talked about being able to share Java libraries across apps, so one didn't have to download e.g. the Android support library 293589235 times. Maybe this behaviour is fucked up in our setup?

**Comment by jamuir** [comment]
> Does it just happen on Oreo?

Yes, it's an oreo-only issue.

**Comment by jamuir** [comment]
I downloaded `open_gapps-arm64-8.1-pico-20180704.zip` and examined the `support.v7.app` imports in Phonesky.apk.  You can see from the output below that that version of the apk includes the class `AppCompatViewInflater`:

```
$ tar xf Core/vending-arm.tar
$ unzip -p vending-arm/240-320-480/priv-app/Phonesky/Phonesky.apk classes.dex | strings | grep v7/app
8Landroid/support/v7/app/AlertController$RecycleListView;
(Landroid/support/v7/app/AlertController;
.Landroid/support/v7/app/AppCompatViewInflater;
Landroid/support/v7/app/a;
Landroid/support/v7/app/aa;
Landroid/support/v7/app/ab;
Landroid/support/v7/app/ac;

<snip>
```

When I do the same for the Phonesky apk in my tree, I find that class is missing (see output below).

```
$ unzip -p vendor/opengapps/sources/arm/priv-app/com.android.vending/14/240-320-480/80950900.apk classes.dex | strings | grep v7/app
8Landroid/support/v7/app/AlertController$RecycleListView;
(Landroid/support/v7/app/AlertController;
Landroid/support/v7/app/a;
Landroid/support/v7/app/aa;
Landroid/support/v7/app/ab;
Landroid/support/v7/app/ac;

<snip>
```

So, it may just be a bad apk.

I will try updating the apk and see if the defect goes away.

**Comment by alviteri** [comment]
Good James

**Comment by jamuir** [comment]
https://github.com/opengapps/arm/tree/master/priv-app/com.android.vending

the latest Phonesky apk contains the missing class, so this was fixed as some point.

**Comment by alviteri** [comment]
Did a refresh build today and still the same problem 
![screenshot_20180712-111005](https://user-images.githubusercontent.com/5174751/42623860-436a1522-85c4-11e8-82fa-5f4b37f561ce.png)

**Comment by jamuir** [comment]
:-(  I suspected that might happen.

thanks for trying it out.  I will keep digging.

**Comment by jamuir** [comment]
`open_gapps-arm64-8.1-nano-20180705.zip`

For comparison, I've tried installing the opengapps nano package above via twrp on an n5x.

The installation seems to complete correctly, but after rebooting there are no google apps visible in the app drawer (this includes Play Store).  The install is somehow broken.  :-(

**Comment by jamuir** [comment]
The problem I had installing the open-gapps zip was due to dm-verity.

The changes made to the system image during the install were treated as errors and "corrected" by the kernel on boot.

After dropping the verity mount option, I've been able to successfully install the open-gapps zip.  **I can confirm that the download pending issue does not happen** when gapps are installed via zip package.

Attached is a file list from the nano open-gapps zip.

[nano-file-list.txt](https://github.com/opengapps/aosp_build/files/2202658/nano-file-list.txt)

**Comment by phhusson** [comment]
Could you do a diff of find /system before/after?

Le mar. 17 juil. 2018 à 19:19, James Muir <notifications@github.com> a
écrit :

**Comment by jamuir** [comment]
@phhusson:  sure, but I find that `comm` is a better tool for comparing file-lists.

The indented files listed below were added by the gapps install script.

The non-indented files were dropped by the gapps install script.

```bash
$ comm -3 before.txt after.txt

        /system/addon.d/70-gapps.sh    0ac4a9364a09b7e20342285c60bc4176
/system/app/BookmarkProvider/BookmarkProvider.apk    0c00541315aa5a0c88b0cc6c43ce2144
/system/app/BookmarkProvider/oat/arm64/BookmarkProvider.odex    bc6ddeb24fdda383b9128753b67fdd1d
/system/app/BookmarkProvider/oat/arm64/BookmarkProvider.vdex    592fd5ac159966bcdc84930369749224
/system/app/ExtShared/ExtShared.apk    c6045eba59a659d757c75427ad6473f1
/system/app/ExtShared/oat/arm64/ExtShared.odex    bebd6ec9c52c879aca3bb84eca996ab1
/system/app/ExtShared/oat/arm64/ExtShared.vdex    6a508513779c5c0cd6dbe95fe67b606b
        /system/app/FaceLock/FaceLock.apk    fc7102d328442d078ad5902b117ba121
        /system/app/GoogleCalendarSyncAdapter/GoogleCalendarSyncAdapter.apk    1442d2f2c5ec83efd788d8ce9815978c
        /system/app/GoogleContactsSyncAdapter/GoogleContactsSyncAdapter.apk    c8e71e498eccf228b3dad6aa879b63cd
        /system/app/GoogleExtShared/GoogleExtShared.apk    f2285c1c8ebce0156e949a485e54c9fc
        /system/app/GoogleTTS/GoogleTTS.apk    055a4350677cfbbe223a986859722385
/system/app/QuickSearchBox/oat/arm64/QuickSearchBox.odex    7e1c216355e7588e9a58c1d512ece5e2
/system/app/QuickSearchBox/oat/arm64/QuickSearchBox.vdex    4adc7a5c0491523f80dce860160fdf65
/system/app/QuickSearchBox/QuickSearchBox.apk    591bf09c19890afde82b8ca5b74019df
        /system/etc/default-permissions/default-permissions.xml    6c92d5863dcf94468f39279a7f1b3e45
        /system/etc/default-permissions/opengapps-permissions.xml    026c0de08a451c7308372cd8f876f8f5
        /system/etc/g.prop    b9326b8d8e3d71f1f7fb8dfaaed849e1
/system/etc/permissions/com.google.android.camera.experimental2016.xml    b16dd6f3c59fde1cadfcc10780cc1d2c
        /system/etc/permissions/com.google.android.dialer.support.xml    e0735cb897c0795169be9f76ef6a2096
        /system/etc/permissions/com.google.android.maps.xml    5575cd792eaa706fa54a7465b7e12be3
        /system/etc/permissions/com.google.android.media.effects.xml    86293a6533a2e6dabc6cd7748d0f3d6e
        /system/etc/permissions/com.google.widevine.software.drm.xml    a3ddc5b8ff1912caf8e76f1491c50067
        /system/etc/permissions/privapp-permissions-google.xml    56238c501fec63c846195eee2c032e06
        /system/etc/preferred-apps/google.xml    247eb4823b8f34ba3b1704e4161b0531
        /system/etc/sysconfig/dialer_experience.xml    a3c03780d49c9ac6684c0a6870f584c7
        /system/etc/sysconfig/google_build.xml    570b6240113590828490dcf65557a3e7
        /system/etc/sysconfig/google.xml    3fa6a594bd9681c3ff5d93d4cb178300
        /system/framework/com.google.android.dialer.support.jar    83dcb232808d87cf575259057ffc13d1
        /system/framework/com.google.android.maps.jar    91c86986f770242667e6ce185bd593d9
        /system/framework/com.google.android.media.effects.jar    b4979b3249a04af54e56db1b3ffa10ed
        /system/framework/com.google.widevine.software.drm.jar    9c0788c6c79a3a9e989ec6d3e03fb851
        /system/lib64/libfacenet.so    06093c241eab70f7e3122949af395091
        /system/lib64/libfilterpack_facedetect.so    32da41530f4dbf77f6b07dc5fe5507fa
        /system/lib64/libfrsdk.so    621760b852ee6d36a6f1291cdf81022b
        /system/lib64/libjni_latinimegoogle.so    f8fb3f169fdd80d6ab68e031910bfe0b
        /system/lib/libfilterpack_facedetect.so    2a9ebbd2b95c26e8ab973ca146734aed
        /system/lib/libfrsdk.so    bbf2b1454823be8b1492185ceae35eb3
        /system/priv-app/ConfigUpdater/ConfigUpdater.apk    bd38f092833fbb67231198e7c8c968b6
/system/priv-app/ExtServices/ExtServices.apk    bfc6132c0e981b9ec8bf39e2599bfc84
/system/priv-app/ExtServices/oat/arm64/ExtServices.odex    54cfa2f94668fe32ceedaf084a215368
/system/priv-app/ExtServices/oat/arm64/ExtServices.vdex    ac7c4ddd1f2f7351d0a9e70ca64ea72d
        /system/priv-app/GmsCoreSetupPrebuilt/GmsCoreSetupPrebuilt.apk    a76b79b3b9c951ceb7cd8bb425f26647
        /system/priv-app/GoogleBackupTransport/GoogleBackupTransport.apk    77626cfe57af73add0a9893a667d8dec
        /system/priv-app/GoogleExtServices/GoogleExtServices.apk    3a930f77ed4224cd0bfb3418ad5024c0
        /system/priv-app/GoogleFeedback/GoogleFeedback.apk    c579a71d0953bf0758c2418efda21aec
        /system/priv-app/GoogleOneTimeInitializer/GoogleOneTimeInitializer.apk    0b51bd02d50b4b00e07a03b5bc85a344
        /system/priv-app/GooglePackageInstaller/GooglePackageInstaller.apk    847ec936034b74bfeb932ff1cc8dc14a
        /system/priv-app/GooglePartnerSetup/GooglePartnerSetup.apk    35c1025066c2a678bc8655ed7d12dc1a
        /system/priv-app/GoogleServicesFramework/GoogleServicesFramework.apk    58f877982845e339d028a338e1a515bc
/system/priv-app/OneTimeInitializer/oat/arm64/OneTimeInitializer.odex    d2d90f1f5aa7181901e40058016e1233
/system/priv-app/OneTimeInitializer/oat/arm64/OneTimeInitializer.vdex    c83311867d5b664aa08102dfd11f8e0b
/system/priv-app/OneTimeInitializer/OneTimeInitializer.apk    43ad8d05af05dd79155d0239d7da369d
/system/priv-app/PackageInstaller/oat/arm64/PackageInstaller.odex    a9592a62ba783cb7b4a5c838c7fbe4ee
/system/priv-app/PackageInstaller/oat/arm64/PackageInstaller.vdex    849059ca7cef51756d8218ae1926f961
/system/priv-app/PackageInstaller/PackageInstaller.apk    3a61abba9ec10fc427a758a6ae8cf307
        /system/priv-app/Phonesky/Phonesky.apk    519bbc21b234aa520b21f3705ec48b71
        /system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk    858fe4c5eddbf7d51d699ea5622a20fe
/system/priv-app/Provision/oat/arm64/Provision.odex    3987992b9c73d71895381d8188146185
/system/priv-app/Provision/oat/arm64/Provision.vdex    fa338ca6cbcbd39ae690a30e90bfcb01
/system/priv-app/Provision/Provision.apk    1f55ac2f3f3a4d069c27c547cd489d27
        /system/priv-app/SetupWizard/SetupWizard.apk    514ddc84f97b9d38ddedbd75b4eaa376
        /system/priv-app/Turbo/Turbo.apk    69eb27385c9b0b2e1e1ea0c9e020af9a
        /system/priv-app/Velvet/Velvet.apk    1cd00b5f8b058ecb8cf5b886fcf6e0af
        /system/usr/srec/en-US/am_phonemes.syms    feb5518f4072c04bbd0a46ec330c8e2b
        /system/usr/srec/en-US/app_bias.fst    a560e5c3d334b661ac0d9b8e1b8a024c
        /system/usr/srec/en-US/APP_NAME.fst    fb246ac37da048b8175072b5aa8cca39
        /system/usr/srec/en-US/APP_NAME.syms    c6f05af58ee74ac945605fb1bfb4d2af
        /system/usr/srec/en-US/c_fst    423759e3d0647cb68b856cbcebbd971f
        /system/usr/srec/en-US/CLG.prewalk.fst    695f9864ef7cb44e8df6cebac5a99bca
        /system/usr/srec/en-US/commands.abnf    efeba35308b66554282112260e1ede98
        /system/usr/srec/en-US/compile_grammar.config    861a0153ddbafa1102b96f0fe15ae31e
        /system/usr/srec/en-US/config.pumpkin    84d2dbe967d21ac8ea2c3f9519bfbcf4
        /system/usr/srec/en-US/confirmation_bias.fst    ef329a7bf195db6ed866e42bd7ae23bc
        /system/usr/srec/en-US/CONTACT_NAME.fst    fb246ac37da048b8175072b5aa8cca39
        /system/usr/srec/en-US/CONTACT_NAME.syms    c6f05af58ee74ac945605fb1bfb4d2af
        /system/usr/srec/en-US/contacts.abnf    c31b71b6cfb1275934e8c69471ecc28b
        /system/usr/srec/en-US/contacts_bias.fst    a95fec6ef4c9685cfba6f15e6889bc05
        /system/usr/srec/en-US/contacts_disambig.fst    9dd0338838e8193d0de49766a4e81f44
        /system/usr/srec/en-US/dict    0de50ccaddfda3ff14cd9052d6f23886
        /system/usr/srec/en-US/dictation.config    cc4c054ce963905fb29c8bdcb400d255
        /system/usr/srec/en-US/dnn    9518034e53147a8b0f2c98088a45b172
        /system/usr/srec/en-US/embedded_class_denorm.mfar    4504704b00f992d83e93b72faf72255e
        /system/usr/srec/en-US/embedded_normalizer.mfar    434009aa0bcf7f68af1db0f592fe3a80
        /system/usr/srec/en-US/endpointer_dictation.config    8a959e56d6fe943143c820ea4d6cd9a6
        /system/usr/srec/en-US/endpointer_model    13fbde85222d7b529027fd8bbf388797
        /system/usr/srec/en-US/endpointer_model.mmap    13fbde85222d7b529027fd8bbf388797
        /system/usr/srec/en-US/endpointer_voicesearch.config    b8ec986c60c500574a5b7d4e53177550
        /system/usr/srec/en-US/ep_portable_mean_stddev    02dff35cf6e0baf836c2f76e412bbfb5
        /system/usr/srec/en-US/ep_portable_model.uint8.mmap    92dabdbf9318a6cf1f6ec85b8f11539f
        /system/usr/srec/en-US/g2p.data    006ef64f514540c94aa3b699f4cdaa0b
        /system/usr/srec/en-US/g2p_fst    29f79efc29484b143e322de47d2b1001
        /system/usr/srec/en-US/g2p_graphemes.syms    34105ccff6b5f291a67c2d56d9b6765e
        /system/usr/srec/en-US/g2p_phonemes.syms    0d8c727ac69015bdef17faa07a48be62
        /system/usr/srec/en-US/grammar.config    995e0ca9fabc61627bda42eb3e23a649
        /system/usr/srec/en-US/hmmlist    798967b0814c55c7260f2fcc5ca9548e
        /system/usr/srec/en-US/hmm_symbols    b1f0b37724cd0204a035d08ce66949ab
        /system/usr/srec/en-US/input_mean_std_dev    5b03e25a5dfa3ad7a1c6a44115e192f3
        /system/usr/srec/en-US/lexicon.U.fst    c50372923c845b37cb21b45580bd091b
        /system/usr/srec/en-US/lstm_model.uint8.data    e8b737c215ea200da0e0f2b0d866fda2
        /system/usr/srec/en-US/magic_mic.config    07859b6ccc0d003b0fe7762e48d35cab
        /system/usr/srec/en-US/media_bias.fst    b9919e8cf43ca4dded31e7c2fcaee8ae
        /system/usr/srec/en-US/metadata    34ffbf8309851def61a9129809527d70
        /system/usr/srec/en-US/monastery_config.pumpkin    ea66f3e41119970312560c0c8ea7c04c
        /system/usr/srec/en-US/norm_fst    801c39261c14ee794b046f834c18aeb2
        /system/usr/srec/en-US/offensive_word_normalizer.mfar    2be464249c201f65241e296833a37209
        /system/usr/srec/en-US/offline_action_data.pb    6d4ee204df9a49e4daaa680100b97b9a
        /system/usr/srec/en-US/phonelist    2a3f21848402442385351cc4e8cf665d
        /system/usr/srec/en-US/portable_lstm    aeb587ea1a5ca1c2d2cde9b3af1653ce
        /system/usr/srec/en-US/portable_meanstddev    970ad8317ec3d60ba1800f892d2c4e02
        /system/usr/srec/en-US/pumpkin.mmap    b10fc66c8ad91856e0e7b77c531473aa
        /system/usr/srec/en-US/read_items_bias.fst    34fc1563fe947ec5f7c298e34e3e3f6c
        /system/usr/srec/en-US/rescoring.fst.compact    8036b51283ddf06ffc1560076235b18d
        /system/usr/srec/en-US/semantics.pumpkin    a4304d2c1ef06af89c32ddedfb4adf48
        /system/usr/srec/en-US/skip_items_bias.fst    91d6c82d110f29fba2a6d2df20517647
        /system/usr/srec/en-US/SONG_NAME.fst    fb246ac37da048b8175072b5aa8cca39
        /system/usr/srec/en-US/SONG_NAME.syms    c6f05af58ee74ac945605fb1bfb4d2af
        /system/usr/srec/en-US/time_bias.fst    f9268692d89c8a442771a952aadf3400
        /system/usr/srec/en-US/transform.mfar    877ceb2ea334b55833597a26229f2668
        /system/usr/srec/en-US/voice_actions_compiler.config    c7a96837b4baf189099c62a13a88fec2
        /system/usr/srec/en-US/voice_actions.config    269840c3ac1d34e60d27416b079b9719
        /system/usr/srec/en-US/word_confidence_classifier    635426b9aa92478a2a9325ae5a6ff087
        /system/usr/srec/en-US/wordlist.syms    e59dfb9d73fbd17ee65b713de10fe459
```

**Comment by phhusson** [comment]
Thanks
so compared to an AOSP build with opengapps integration I get:
opengapps zip removes BookmarkProvider ExtShared ExtServices
opengapps zip adds GoogleExtShared etc/g.prop lib/libfrsdk.so (lib64/libfrsdk.so is there) ConfigUpdater GoogleExtServices GmsCoreSetupPrebuilt

**Comment by phhusson** [comment]
There is no reference at all of ConfigUpdater or GmsCoreSetupPrebuilt in https://github.com/opengapps/aosp_build.git

**Comment by jamuir** [comment]
i noticed that, too.

I will open PR today or tomorrow where I'll try to resolve the differences with the install script.

**Comment by jamuir** [comment]
Good news.  There is a quick fix to resolve the "Download pending..." issue:  **just drop PrebuiltGmsCoreInstantApps**.

I've checked that this works in two different builds.

I will open a PR for this in a few minutes.

The more involved issue here is that `aosp_build` is out of sync with `installer.sh` (from the opengapps zips).  I've been working on addressing that, but, unfortunately, that is not a quick fix :-)

**Comment by alviteri** [comment]
So that can be the reason why it is not included in Sony stock releases ... I don't know Google (pixel) good to know ... Thanks james
