### ISSUE TITLE
Chrome crashing because cannot load libchrome.so

### ISSUE THREAD

**Issue by aaboyd** [opengapps/aosp_build#21]
Any clue where I could look to figure out why libchrome.so isn't loaded?

I'm doing a build based off of CM 12 ( Android 5.0.2 ).

```
I/cr_LibraryLoader(10337): Using linker: org.chromium.base.library_loader.LegacyLinker
I/cr_LibraryLoader(10337): Loading chrome from within /system/app/Chrome/Chrome.apk
E/cr_ChromiumAndroidLinker(10337): Open: Could not open libchrome.so in zip file /system/app/Chrome/Chrome.apk: (null)
E/cr_LibraryLoader(10337): Unable to load library: libchrome.so, in: /system/app/Chrome/Chrome.apk
E/NativeInitializationController(10337): Unable to load native library.
E/NativeInitializationController(10337): org.chromium.base.library_loader.ProcessInitException
E/NativeInitializationController(10337):        at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:271)
E/NativeInitializationController(10337):        at org.chromium.base.library_loader.LibraryLoader.ensureInitialized(LibraryLoader.java:123)
E/NativeInitializationController(10337):        at org.chromium.chrome.browser.init.NativeInitializationController$1.run(NativeInitializationController.java:84)
E/NativeInitializationController(10337): Caused by: java.lang.UnsatisfiedLinkError: Unable to load library: libchrome.so, in: /system/app/Chrome/Chrome.apk
E/NativeInitializationController(10337):        at org.chromium.base.library_loader.LegacyLinker.loadLibraryImpl(LegacyLinker.java:500)
E/NativeInitializationController(10337):        at org.chromium.base.library_loader.Linker.loadLibrary(Linker.java:569)
E/NativeInitializationController(10337):        at org.chromium.base.library_loader.LibraryLoader.loadLibrary(LibraryLoader.java:205)
E/NativeInitializationController(10337):        at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:250)
E/NativeInitializationController(10337):        ... 2 more
```

**Comment by mfonville** [comment]
I have a suspicion. Probably the 'crazy' libs inside the apk are not kept uncompressed and zipaligned inside the apk. Chrome needs a special treatment...

**Comment by mfonville** [comment]
@Blystad 
bumping this issue.
How does the regular aosp-build process handle APK lib-extraction & preparation? Can we provide it hints to handle certain libs in a different way?

**Comment by Blystad** [comment]
Well, running `mm -B showcommands` in the Chrome folder results in this output:

```
make: Entering directory `/home/blystad/x7k/android/lollipop'
target Prebuilt: Chrome (/home/blystad/x7k/android/lollipop/out/target/product/x7k/obj/APPS/Chrome_intermediates/package.apk)
/home/blystad/x7k/android/lollipop/out/host/linux-x86/bin/acp -fp vendor/opengapps/sources/arm/app/com.android.chrome/21/nodpi/249007601.apk /home/blystad/x7k/android/lollipop/out/target/product/x7k/obj/APPS/Chrome_intermediates/package.apk
zip -d /home/blystad/x7k/android/lollipop/out/target/product/x7k/obj/APPS/Chrome_intermediates/package.apk 'lib/*.so'  # strip embedded JNI libraries.
deleting: lib/armeabi-v7a/crazy.libchrome.so
deleting: lib/armeabi-v7a/libchrome.1847.114.so
deleting: lib/armeabi-v7a/libchrome.1916.122.so
deleting: lib/armeabi-v7a/libchrome.1916.138.so
deleting: lib/armeabi-v7a/libchrome.1916.141.so
deleting: lib/armeabi-v7a/libchrome.1985.122.so
deleting: lib/armeabi-v7a/libchrome.1985.128.so
deleting: lib/armeabi-v7a/libchrome.1985.131.so
deleting: lib/armeabi-v7a/libchrome.1985.135.so
deleting: lib/armeabi-v7a/libchrome.2062.117.so
deleting: lib/armeabi-v7a/libchrome.2125.102.so
deleting: lib/armeabi-v7a/libchrome.2125.114.so
deleting: lib/armeabi-v7a/libchrome.2171.37.so
deleting: lib/armeabi-v7a/libchrome.2171.59.so
deleting: lib/armeabi-v7a/libchromeview.so
deleting: lib/armeabi-v7a/libchromium_android_linker.so
mv /home/blystad/x7k/android/lollipop/out/target/product/x7k/obj/APPS/Chrome_intermediates/package.apk /home/blystad/x7k/android/lollipop/out/target/product/x7k/obj/APPS/Chrome_intermediates/package.apk.unaligned
/home/blystad/x7k/android/lollipop/out/host/linux-x86/bin/zipalign -f 4 /home/blystad/x7k/android/lollipop/out/target/product/x7k/obj/APPS/Chrome_intermediates/package.apk.unaligned /home/blystad/x7k/android/lollipop/out/target/product/x7k/obj/APPS/Chrome_intermediates/   package.apk.aligned
mv /home/blystad/x7k/android/lollipop/out/target/product/x7k/obj/APPS/Chrome_intermediates/package.apk.aligned /home/blystad/x7k/android/lollipop/out/target/product/x7k/obj/APPS/Chrome_intermediates/package.apk
Extract JNI libs (/home/blystad/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.1847.114.so <- vendor/opengapps/sources/arm/app/com.android.chrome/21/nodpi/249007601.apk)
unzip -j -o -d /home/blystad/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/ vendor/opengapps/sources/arm/app/com.android.chrome/21/nodpi/249007601.apk lib/armeabi-v7a/libchrome.1847.114.so lib/armeabi-v7a/libchrome.1916.122.so lib/armeabi-   v7a/libchrome.1916.138.so lib/armeabi-v7a/libchrome.1916.141.so lib/armeabi-v7a/libchrome.1985.122.so lib/armeabi-v7a/libchrome.1985.128.so lib/armeabi-v7a/libchrome.1985.131.so lib/armeabi-v7a/libchrome.1985.135.so lib/armeabi-v7a/libchrome.2062.117.so lib/armeabi-v7a/   libchrome.2125.102.so lib/armeabi-v7a/libchrome.2125.114.so lib/armeabi-v7a/libchrome.2171.37.so lib/armeabi-v7a/libchrome.2171.59.so lib/armeabi-v7a/libchromeview.so lib/armeabi-v7a/libchromium_android_linker.so && touch /home/blystad/x7k/android/lollipop/out/target/     product/x7k/system/google/app/Chrome/lib/arm/libchrome.1847.114.so
Archive:  vendor/opengapps/sources/arm/app/com.android.chrome/21/nodpi/249007601.apk
  inflating: /home/blystad/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.1847.114.so 
  inflating: /home/blystad/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.1916.122.so 
  inflating: /home/blystad/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.1916.138.so 
  inflating: /home/blystad/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.1916.141.so 
  inflating: /home/blystad/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.1985.122.so 
  inflating: /home/blystad/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.1985.128.so 
  inflating: /home/blystad/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.1985.131.so 
  inflating: /home/blystad/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.1985.135.so 
  inflating: /home/blystad/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.2062.117.so 
  inflating: /home/blystad/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.2125.102.so 
  inflating: /home/blystad/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.2125.114.so 
  inflating: /home/blystad/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.2171.37.so 
  inflating: /home/blystad/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.2171.59.so 
  inflating: /home/blystad/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchromeview.so 
  inflating: /home/blystad/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchromium_android_linker.so 
Install: /home/blystad/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/Chrome.apk
/home/blystad/x7k/android/lollipop/out/host/linux-x86/bin/acp -fp /home/blystad/x7k/android/lollipop/out/target/product/x7k/obj/APPS/Chrome_intermediates/package.apk /home/blystad/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/Chrome.apk
make: Leaving directory `/home/blystad/x7k/android/lollipop'
```

Which originates from this:
```
182 # Sign and align non-presigned .apks.
183 $(built_module) : $(my_prebuilt_src_file) | $(ACP) $(ZIPALIGN) $(SIGNAPK_JAR)
184     $(transform-prebuilt-to-target)
185 ifdef extracted_jni_libs
186     $(hide) zip -d $@ 'lib/*.so'  # strip embedded JNI libraries.
187 endif
188 ifneq ($(LOCAL_CERTIFICATE),PRESIGNED)
189     $(sign-package)
190 endif
191 ifdef LOCAL_DEX_PREOPT
192 ifneq (nostripping,$(LOCAL_DEX_PREOPT))
193     $(call dexpreopt-remove-classes.dex,$@)
194 endif
195 endif
196     $(align-package)
```

Easy way would be to just provide a patch for the AOSP build system to filter out crazy. Ideal way would be to handle this in some way from just the opengapps system. I don't know if it's worth figuring out that way, or if a patch is just the easiest solution, seeing as Lollipop is starting to age now, and Marshmallow fixes this.

**Comment by mfonville** [comment]
@Blystad I think it would be worthwhile to fix it, because I think 5.1 will stick around for still quite some time. Many devices were released with 5(.1) drivers that don't work on MM+.
Also the fix should be not too hard. Unfortunately `zip` doesn't allow to overwrite an earlier exclude with an include, so the fix should mimic the Open GApps buildhelper script with listing the libs and deleting them using `xarg zip`. Change line 186 to:
```
for apk in "$@"; do
  unzip -Z -1 "$apk" | grep "lib/" | grep -v "/crazy." | xargs zip -d "$apk"
done
```

**Comment by Blystad** [comment]
I'm for fixing it, but against spending lots of time on it :)

```
make: Entering directory `/home/pixavi/x7k/android/lollipop'
target Prebuilt: Chrome (/home/pixavi/x7k/android/lollipop/out/target/product/x7k/obj/APPS/Chrome_intermediates/package.apk)
/home/pixavi/x7k/android/lollipop/out/host/linux-x86/bin/acp -fp vendor/opengapps/sources/arm/app/com.android.chrome/21/nodpi/249007601.apk /home/pixavi/x7k/android/lollipop/out/target/product/x7k/obj/APPS/Chrome_intermediates/package.apk
unzip -Z -1 /home/pixavi/x7k/android/lollipop/out/target/product/x7k/obj/APPS/Chrome_intermediates/package.apk | grep "lib/" | grep -v "/crazy." | xargs zip -d /home/pixavi/x7k/android/lollipop/out/target/product/x7k/obj/APPS/Chrome_intermediates/package.apk # strip embedded JNI libraries.
deleting: lib/armeabi-v7a/libchrome.1847.114.so
deleting: lib/armeabi-v7a/libchrome.1916.122.so
deleting: lib/armeabi-v7a/libchrome.1916.138.so
deleting: lib/armeabi-v7a/libchrome.1916.141.so
deleting: lib/armeabi-v7a/libchrome.1985.122.so
deleting: lib/armeabi-v7a/libchrome.1985.128.so
deleting: lib/armeabi-v7a/libchrome.1985.131.so
deleting: lib/armeabi-v7a/libchrome.1985.135.so
deleting: lib/armeabi-v7a/libchrome.2062.117.so
deleting: lib/armeabi-v7a/libchrome.2125.102.so
deleting: lib/armeabi-v7a/libchrome.2125.114.so
deleting: lib/armeabi-v7a/libchrome.2171.37.so
deleting: lib/armeabi-v7a/libchrome.2171.59.so
deleting: lib/armeabi-v7a/libchromeview.so
deleting: lib/armeabi-v7a/libchromium_android_linker.so
mv /home/pixavi/x7k/android/lollipop/out/target/product/x7k/obj/APPS/Chrome_intermediates/package.apk /home/pixavi/x7k/android/lollipop/out/target/product/x7k/obj/APPS/Chrome_intermediates/package.apk.unaligned
/home/pixavi/x7k/android/lollipop/out/host/linux-x86/bin/zipalign -f 4 /home/pixavi/x7k/android/lollipop/out/target/product/x7k/obj/APPS/Chrome_intermediates/package.apk.unaligned /home/pixavi/x7k/android/lollipop/out/target/product/x7k/obj/APPS/Chrome_intermediates/package.apk.aligned
mv /home/pixavi/x7k/android/lollipop/out/target/product/x7k/obj/APPS/Chrome_intermediates/package.apk.aligned /home/pixavi/x7k/android/lollipop/out/target/product/x7k/obj/APPS/Chrome_intermediates/package.apk
Extract JNI libs (/home/pixavi/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.1847.114.so <- vendor/opengapps/sources/arm/app/com.android.chrome/21/nodpi/249007601.apk)
unzip -j -o -d /home/pixavi/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/ vendor/opengapps/sources/arm/app/com.android.chrome/21/nodpi/249007601.apk lib/armeabi-v7a/libchrome.1847.114.so lib/armeabi-v7a/libchrome.1916.122.so lib/armeabi-v7a/libchrome.1916.138.so lib/armeabi-v7a/libchrome.1916.141.so lib/armeabi-v7a/libchrome.1985.122.so lib/armeabi-v7a/libchrome.1985.128.so lib/armeabi-v7a/libchrome.1985.131.so lib/armeabi-v7a/libchrome.1985.135.so lib/armeabi-v7a/libchrome.2062.117.so lib/armeabi-v7a/libchrome.2125.102.so lib/armeabi-v7a/libchrome.2125.114.so lib/armeabi-v7a/libchrome.2171.37.so lib/armeabi-v7a/libchrome.2171.59.so lib/armeabi-v7a/libchromeview.so lib/armeabi-v7a/libchromium_android_linker.so && touch /home/pixavi/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.1847.114.so
Archive:  vendor/opengapps/sources/arm/app/com.android.chrome/21/nodpi/249007601.apk
  inflating: /home/pixavi/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.1847.114.so  
  inflating: /home/pixavi/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.1916.122.so  
  inflating: /home/pixavi/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.1916.138.so  
  inflating: /home/pixavi/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.1916.141.so  
  inflating: /home/pixavi/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.1985.122.so  
  inflating: /home/pixavi/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.1985.128.so  
  inflating: /home/pixavi/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.1985.131.so  
  inflating: /home/pixavi/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.1985.135.so  
  inflating: /home/pixavi/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.2062.117.so  
  inflating: /home/pixavi/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.2125.102.so  
  inflating: /home/pixavi/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.2125.114.so  
  inflating: /home/pixavi/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.2171.37.so  
  inflating: /home/pixavi/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchrome.2171.59.so  
  inflating: /home/pixavi/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchromeview.so  
  inflating: /home/pixavi/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/lib/arm/libchromium_android_linker.so  
Install: /home/pixavi/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/Chrome.apk
/home/pixavi/x7k/android/lollipop/out/host/linux-x86/bin/acp -fp /home/pixavi/x7k/android/lollipop/out/target/product/x7k/obj/APPS/Chrome_intermediates/package.apk /home/pixavi/x7k/android/lollipop/out/target/product/x7k/system/google/app/Chrome/Chrome.apk
make: Leaving directory `/home/pixavi/x7k/android/lollipop'
```

With the following patch:
```
diff --git a/core/prebuilt_internal.mk b/core/prebuilt_internal.mk
index bc6088f..03bcf1f 100644
--- a/core/prebuilt_internal.mk
+++ b/core/prebuilt_internal.mk
@@ -183,7 +183,7 @@ include $(BUILD_SYSTEM)/dex_preopt_odex_install.mk
 $(built_module) : $(my_prebuilt_src_file) | $(ACP) $(ZIPALIGN) $(SIGNAPK_JAR)
        $(transform-prebuilt-to-target)
 ifdef extracted_jni_libs
-       $(hide) zip -d $@ 'lib/*.so'  # strip embedded JNI libraries.
+       $(hide) unzip -Z -1 $@ | grep "lib/" | grep -v "/crazy." | xargs zip -d $@ # strip embedded JNI libraries.
 endif
 ifneq ($(LOCAL_CERTIFICATE),PRESIGNED)
        $(sign-package)
```

I guess that's closer to what you expect?

**Comment by mfonville** [comment]
Looks good to me :+1: 

This automatically also works correctly on MM+? (i.e. `ifdef extracted_jni_libs` is set to false?)

**Comment by Blystad** [comment]
This part of the build system was removed in M:

```
commit 1fb0152ff7bf24b565b44a57e51290f2a5430107
Author: Ying Wang <wangying@google.com>
Date:   Fri May 1 14:02:26 2015 -0700

    Don't extract jni from prebuilt apks.
    
    - We don't need LOCAL_PAGE_ALIGN_JNI_SHARED_LIBRARIES now, for we always
      page-align jni shared libraries and store them umcompressed.
    - For prebuilt apks, we don't extract jni any more; Instead we always run
      uncompress-shared-libs on them.
    - For apks built from source, we still install the jni separately, because
      that way multiple apks can share the same jni and it saves space.
    
    With this change, for most prebuilt apks, we don't need to specify
    LOCAL_PREBUILT_JNI_LIBS ("@lib/<abi>/foo.so") any more, for the build
    system automatically replaces the embedded jni with uncompressed files;
    But if a prebuilt is a fat apk (i.e. containing jni not needed by the
    current product architecture), you still need LOCAL_PREBUILT_JNI_LIBS to
    specify what jni to keep. Otherwise all embedded jni will be replaced with
    uncompressed files, that wastes space.
    
    Bug: 8076853
    Change-Id: Ic3666dc72bf17cd293787414dd185470b365f967
```
