### ISSUE TITLE
Open Gapps not syncing with repo sync -c -d --force-sync 

### ISSUE THREAD

**Issue by BAProductions** [opengapps/aosp_build#228]
```

remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0        
Fetching project all
warning: redirecting to https://gitlab.opengapps.org/opengapps/all.git/
remote: Total 0 (delta 0), reused 0 (delta 0)        
Fetching projects: 100% (1/1)
Fetching projects: 100% (1/1), done.
Checking out project all
git-lfs filter-process --skip: 1: git-lfs filter-process --skip: git-lfs: not found
fatal: The remote end hung up unexpectedly
error: Cannot checkout all: GitError: cannot initialize work tree for all
Traceback (most recent call last):
  File "/home/android/lineage-16.0/.repo/repo/main.py", line 530, in <module>
    _Main(sys.argv[1:])
  File "/home/android/lineage-16.0/.repo/repo/main.py", line 505, in _Main
    result = run()
  File "/home/android/lineage-16.0/.repo/repo/main.py", line 498, in <lambda>
    run = lambda: repo._Run(name, gopts, argv) or 0
  File "/home/android/lineage-16.0/.repo/repo/main.py", line 201, in _Run
    result = cmd.Execute(copts, cargs)
  File "/home/android/lineage-16.0/.repo/repo/subcmds/sync.py", line 1001, in Execute
    self._Checkout(all_projects, opt)
  File "/home/android/lineage-16.0/.repo/repo/subcmds/sync.py", line 554, in _Checkout
    self._CheckoutWorker(**kwargs)
  File "/home/android/lineage-16.0/.repo/repo/subcmds/sync.py", line 439, in _CheckoutWorker
    return self._CheckoutOne(opt, project, *args, **kwargs)
  File "/home/android/lineage-16.0/.repo/repo/subcmds/sync.py", line 474, in _CheckoutOne
    project.Sync_LocalHalf(syncbuf, force_sync=opt.force_sync)
  File "/home/android/lineage-16.0/.repo/repo/project.py", line 1508, in Sync_LocalHalf
    self._InitWorkTree(force_sync=force_sync, submodules=submodules)
  File "/home/android/lineage-16.0/.repo/repo/project.py", line 2735, in _InitWorkTree
    raise GitError("cannot initialize work tree for " + self.name)
error.GitError: cannot initialize work tree for all
```

**Comment by nezorflame** [comment]
Please check https://github.com/opengapps/aosp_build/pull/227
In short, we've recreated our repos from scratch and are now using Git LFS: https://git-lfs.github.com/.
Please make sure you've installed it on your machine before pulling.

**Comment by BAProductions** [comment]
Thanks
