### ISSUE TITLE
No Webview implementation available (Android 9)

### ISSUE THREAD

**Issue by codevalley** [opengapps/aosp_build#233]
This is my first time adding Open Gapps to my AOSP codebase. 
I have made changes to device.mk.
I have tried different combinations in terms of build variants (pico to stock), different exclusion, force rules, but irrespective of what I try I get this error. 
```
WebViewFactory: Chromium WebView package does not exist
WebViewFactory: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
```

This basically stalls, the Out of the box setup experience (or pretty much any screen that requires Google account creation/fetching, as it uses a webview).
In the developer options, `Webview` Implementation is `none`. It does not show any options either. 

I am building my AOSP for Pixel 2(Walleye).

**Comment by codevalley** [comment]
Things are working fine on `pico` variant. But when I use a larger variant like `stock` (which replaces AOSP webview) things are breaking.

**Comment by hmj1235** [comment]
Hi,
    I got the same issue as your are, but my device is pixel3. The webview is lost when choose stock.

**Comment by stefanhh0** [comment]
With the integration of: 
- opengapps/aosp_build/commit/fd0c1404e0dae454a18406ea1bb9cca007b369a9
- opengapps/aosp_build/commit/55ed81dc78db26a95a67d242b49696259368af2d
- opengapps/aosp_build/commit/85625c1195c9354c6d19ce5f825e219314af35c3

The problem should be fixed, please verify and close this if you can confirm.

**Comment by codevalley** [comment]
Will check and confirm the fix @stefanhh0

**Comment by codevalley** [comment]
The above commits did not fix the issue. Still getting missing webview issue on building `stock`.
This are the logs.
```
03-11 07:03:42.874  7022  7022 E WebViewFactory: Chromium WebView package does not exist
03-11 07:03:42.874  7022  7022 E WebViewFactory: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:376)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:439)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:251)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at android.webkit.CookieManager.getInstance(CookieManager.java:40)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at kar.a(:com.google.android.gms@19668028@19.6.68 (100400-281397792):1)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at jzi.onCreateView(:com.google.android.gms@19668028@19.6.68 (100400-281397792):1)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at kch.onCreateView(:com.google.android.gms@19668028@19.6.68 (100400-281397792):1)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at com.google.android.chimera.FragmentProxy.onCreateView(:com.google.android.gms@19668028@19.6.68 (100400-281397792):2)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at ge.a(:com.google.android.gms@19668028@19.6.68 (100400-281397792):7)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at hb.a(:com.google.android.gms@19668028@19.6.68 (100400-281397792):268)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at hb.h(:com.google.android.gms@19668028@19.6.68 (100400-281397792):6)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at hb.a(:com.google.android.gms@19668028@19.6.68 (100400-281397792):26)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at hb.a(:com.google.android.gms@19668028@19.6.68 (100400-281397792):124)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at hb.a(:com.google.android.gms@19668028@19.6.68 (100400-281397792):62)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at hb.j(:com.google.android.gms@19668028@19.6.68 (100400-281397792):11)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at hb.c(:com.google.android.gms@19668028@19.6.68 (100400-281397792):3)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at hb.m(:com.google.android.gms@19668028@19.6.68 (100400-281397792):14)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at gg.onStart(:com.google.android.gms@19668028@19.6.68 (100400-281397792):4)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at duf.superOnStart(Unknown Source:0)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at com.google.android.chimera.Activity.onStart(Unknown Source:2)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at com.google.android.chimera.Activity.publicOnStart(Unknown Source:0)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at qst.onStart(:com.google.android.gms@19668028@19.6.68 (100400-281397792):2)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at android.app.Activity.performStart(Activity.java:7165)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2975)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at android.os.Looper.loop(Looper.java:193)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at java.lang.reflect.Method.invoke(Native Method)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
03-11 07:03:42.874  7022  7022 E WebViewFactory: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
03-11 07:03:42.875  7022  7022 D AndroidRuntime: Shutting down VM
```
