### ISSUE TITLE
SetupWizard Crashes Immediately

### ISSUE THREAD

**Issue by aaboyd** [opengapps/aosp_build#35]
Any ideas welcome!

Not sure what would cause this,  I have tried with `GAPPS_FORCE_MATCHING_DPI := true` and `GAPPS_FORCE_MATCHING_DPI := false` .

```
E/AndroidRuntime( 1981): FATAL EXCEPTION: main
E/AndroidRuntime( 1981): Process: com.google.android.setupwizard, PID: 1981
E/AndroidRuntime( 1981): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.setupwizard/com.google.android.setupwizard.WelcomeActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x1110038
E/AndroidRuntime( 1981): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
E/AndroidRuntime( 1981): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
E/AndroidRuntime( 1981): 	at android.app.ActivityThread.access$900(ActivityThread.java:154)
E/AndroidRuntime( 1981): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
E/AndroidRuntime( 1981): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 1981): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 1981): 	at android.app.ActivityThread.main(ActivityThread.java:5294)
E/AndroidRuntime( 1981): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 1981): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 1981): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime( 1981): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/AndroidRuntime( 1981): Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x1110038
E/AndroidRuntime( 1981): 	at android.content.res.Resources.getValue(Resources.java:1343)
E/AndroidRuntime( 1981): 	at android.content.res.Resources.getValue(Resources.java:1323)
E/AndroidRuntime( 1981): 	at android.content.res.Resources.getBoolean(Resources.java:1055)
E/AndroidRuntime( 1981): 	at com.google.android.setupwizard.WelcomeActivity.initViews(WelcomeActivity.java:543)
E/AndroidRuntime( 1981): 	at com.google.android.setupwizard.WelcomeActivity.onCreate(WelcomeActivity.java:215)
E/AndroidRuntime( 1981): 	at android.app.Activity.performCreate(Activity.java:5990)
E/AndroidRuntime( 1981): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime( 1981): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
E/AndroidRuntime( 1981): 	... 10 more
```

**Comment by mfonville** [comment]
@Blystad I recently splitted out the setupwizards to device-type. Only 4.4 still uses com.google.android.setupwizard as packagename.
For more recent Android versions com.google.android.setupwizard.default should be used. That might fix this issue.

https://github.com/opengapps/all/commit/1de14be43f002316c08f6133e737c2279688cf51

**Comment by aaboyd** [comment]
Thanks @mfonville  that did the trick for me.  I changed it to `com.google.android.setupwizard.default` and it worked.

Anyone know if there is a variable that we can check to see if it is a tablet or not?

Need to use
* `com.google.android.setupwizard` for API <= 19
* `com.google.android.setupwizard.default` for API > 19 and Phone,
* `com.google.android.setupwizard.tablet` for API > 19 and Tablet

**Comment by Blystad** [comment]
```
PRODUCT_CHARACTERISTICS := tablet
```

This property can contain multiple values, e.g. `tablet,sdcard`.

A pull request would be greatly appreciated :)

**Comment by mfonville** [comment]
I do not know anything about the AOSP build-system, but in shell you can probably do:
```
case $PRODUCT_CHARACTERISTICS in
*tablet*) use com.google.android.setupwizard.tablet;;
*) use com.google.android.setupwizard.default;;
esac
```

**Comment by Blystad** [comment]
```
ifneq($(filter $(PRODUCT_CHARACTERISTICS),tablet),)
# this is a tablet
else
# this is a phone
endif
```

**Comment by aaboyd** [comment]
I won't get a chance to do this until after I get back from vacation.  I'll try to put it in next week if I can.

**Comment by Blystad** [comment]
Should be fine now :)
