### ISSUE TITLE
Changes for Nougat

### ISSUE THREAD

**Issue by mfonville** [opengapps/aosp_build#73]
The following changes may need to be ported to aosp_build:
* New config file `/etc/sysconfig/google_vr_build.xml` (all Android versions)
* `/vendor/pittpatt/` seems to be dropped in Nougat
* `libfacelock_jni.so` has been renamed to `libfacenet.so` (Nougat only)
* the keyboard swypelibs have been dropped (Nougat only)
* New app `com.google.vr.vrcore` (all Android versions)
* Path of Google Keyboard has changed to `LatinIMEGooglePrebuilt` (Nougat only)
* New apps `com.google.android.printservice.recommendation`, `com.google.android.ext.shared` and `com.google.android.ext.services` (Nougat only)

**Comment by Blystad** [comment]
Alright, cool. Thanks for the list. Might also be some issues with the entire build system, if they moved it over to the new ninja/kati build system, but will wait for the source drop to see if that's the case.

**Comment by TheCrazyLex** [comment]
@Blystad on N still both build systems are present. There is a compile time flag which disables the new "soong"  build system, however I am not sure whether it works yet. If some repositories use soong makefiles instead of make already, it might not work. 
Otherwise google plans to completely deprecate the old system in the upcoming android releases.

**Comment by Blystad** [comment]
I expected the old one to become deprecated :)

Lets see what happens...I'm currently syncing the nougat source code and plan to have an android device brought up this week.

**Comment by aunali1** [comment]
Hi,

Managed to get the Pixel C running with AOSP Nougat. I'm using the pico variant of Open GApps and applied the Android 6.0 patch.

System boot fines but at the ending of the Setup Wizard it crashes and goes back to account setup section. It always does this loop

Help would be appreciated.

**Comment by Blystad** [comment]
@aunali1 I haven't yet had time to port this to Nougat. Do you have a logcat? then I'll better know what needs to be done.

**Comment by Blystad** [comment]
```
etupwizard/xml/wizard_script_new_device_account_flow actionId=android.resource://com.google.android.setupwizard/xml/wizard_script_new_device_account_flow#user_name_check
08-31 15:44:48.294  1893  2693 W ActivityManager: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{686bad2 2682:com.google.android.setupwizard/u0a27} (pid=2682, uid=10027) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
08-31 15:44:48.305  2682  4299 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
08-31 15:44:48.305  2682  4299 E AndroidRuntime: Process: com.google.android.setupwizard, PID: 2682
08-31 15:44:48.305  2682  4299 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
08-31 15:44:48.305  2682  4299 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:318)
08-31 15:44:48.305  2682  4299 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
08-31 15:44:48.305  2682  4299 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
08-31 15:44:48.305  2682  4299 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
08-31 15:44:48.305  2682  4299 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
08-31 15:44:48.305  2682  4299 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-31 15:44:48.305  2682  4299 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-31 15:44:48.305  2682  4299 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
08-31 15:44:48.305  2682  4299 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{686bad2 2682:com.google.android.setupwizard/u0a27} (pid=2682, uid=10027) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
08-31 15:44:48.305  2682  4299 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1683)
08-31 15:44:48.305  2682  4299 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1636)
08-31 15:44:48.305  2682  4299 E AndroidRuntime: 	at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:4169)
08-31 15:44:48.305  2682  4299 E AndroidRuntime: 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:5434)
08-31 15:44:48.305  2682  4299 E AndroidRuntime: 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2267)
08-31 15:44:48.305  2682  4299 E AndroidRuntime: 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1515)
08-31 15:44:48.305  2682  4299 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:514)
08-31 15:44:48.305  2682  4299 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:472)
08-31 15:44:48.305  2682  4299 E AndroidRuntime: 	at com.google.android.setupwizard.user.ProfileHelper.updateMeContactWith(ProfileHelper.java:61)
08-31 15:44:48.305  2682  4299 E AndroidRuntime: 	at com.google.android.setupwizard.user.NameCheckFragment$1.doInBackground(NameCheckFragment.java:73)
08-31 15:44:48.305  2682  4299 E AndroidRuntime: 	at com.google.android.setupwizard.user.NameCheckFragment$1.doInBackground(NameCheckFragment.java:72)
08-31 15:44:48.305  2682  4299 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:304)
08-31 15:44:48.305  2682  4299 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-31 15:44:48.305  2682  4299 E AndroidRuntime: 	... 4 more
08-31 15:44:48.327  1893  2859 W ActivityManager:   Force finishing activity com.google.android.setupwizard/.time.DateTimeCheck
08-31 15:44:48.364  1893  1905 I WindowManager: Destroying surface Surface(name=com.google.android.setupwizard/com.google.android.setupwizard.account.AccountSetupWrapper) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.destroyOrSaveSurface:2073 com.android.server.wm.WindowManagerService.tryStartExitingAnimation:3017 com.android.server.wm.WindowManagerService.relayoutWindow:2897 com.android.server.wm.Session.relayout:215 android.view.IWindowSession$Stub.onTransact:286 com.android.server.wm.Session.onTransact:136 
08-31 15:44:48.375  2682  2682 I art     : Starting a blocking GC Explicit
```

There's a stacktrace. Now lets see if I can't fix it...

**Comment by Blystad** [comment]
```
08-31 15:39:24.955  1893  1893 E PackageManager: There should probably be exactly one setup wizard; found 2: matches=[ResolveInfo{57cbe0a com.google.android.setupwizard/.SetupWizardActivity p=5 m=0x108000}, ResolveInfo{dc0267b com.android.provision/.DefaultActivity p=1 m=0x108000}]
```

and there's the root cause, for the missing permissions...

**Comment by Blystad** [comment]
If someone can verify PR #76 for me, that would be great. Otherwise I'll merge it in 48 hours.

**Comment by aunali1** [comment]
Alright everything works for me on Pixel C.

Thanks @Blystad !

**Comment by yate** [comment]
- the keyboard swypelibs have been dropped (Nougat only)

Does this mean we need to install google keyboard to use gesture typing?
